Controllers/CalendarController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WillCal.Models;

namespace WillCal.Controllers;

public class CalendarController : Controller
{
    private readonly ILogger<CalendarController> _logger;

    public CalendarController(ILogger<CalendarController> logger)
    {
        _logger = logger;
    }

    public void Index()
    {
        Response.Redirect("/Calendar/CalByDate");
    }

    public IActionResult AddTask() {
        return View(TaskAccess.getCurrentTask());
    }
    
    [HttpPost]
    public void AddTask(TaskData data) {
        Console.WriteLine("sdsdfafasdf");
        TaskAccess.AddEvent(data);
        Response.Redirect("/Calendar/CalByDate");
    }

    public IActionResult CalByDate(string? newDate) {
        ThisMonth.CalByMonth(newDate);
        return View();
    }

    public IActionResult CalWeek(string? newDate) {
        ThisWeek.CalByWeek(newDate);
        return View();
    }

    [HttpGet]
    public IActionResult AddEvent(string? selDate) {
        string[] tmp;
        if(selDate == null)
            tmp = new string[] {DateTime.Today.ToString("d")};
        else {
            tmp = new string[] {selDate.Substring(0,4) + "-" + selDate.Substring(4,2) + "-" + selDate.Substring(6,2), ""};
        }
        return View(tmp);
    }

    [HttpPost]
    public void AddEvent(CalData data) {
        DataAccess.AddEvent(data);
        Response.Redirect("/Calendar/CalByDate");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Calendar/AddEvent.cshtml
@model string[]
@{
    ViewData["Title"] = "Add Event";
}

<div class="container-sm">
    <h3>Enter your event details:</h3>
    <form id="setupForm" action="AddEvent" method="post" name="AddEvent">
        <input type="hidden" name="LineNum" value="1" />
        <fieldset>
            <legend class="text-primary">Event details:</legend>
            <div class="mb-3">
                <label for="EventName" class="form-label">Event Name:</label>
                <input type="text" class="form-control" id="EventName" placeholder="Enter the event name" name="EventName" required>
            </div>
            <div class="mb-3">
                <label for="dtEvent" class="form-label">Event Date:</label>
                <input type="date" class="form-control" id="dtEvent" placeholder="Enter the event date" name="dtEvent" value='@Model[0]' required>
            </div>
        </fieldset>
        <fieldset>
            <legend class="text-primary">Does this event repeat?</legend>
            <div class="mb-3">
                <label for="Repeats" class="form-label">Does this event repeat?</label>
                <label><input type="radio" id="none" name="Repeats" value="False" checked="checked"> No</label>
                <label><input type="radio" id="some" name="Repeats" value="True"> Yes</label>
            </div>
            <div class="mb-3">
                <label for="RepeatBlock" class="form-label">How often does this event repeat?</label>
                <label><input type="radio" id="none" name="RepeatBlock" value="day" checked="checked"> Every x Days</label>
                <label><input type="radio" id="some" name="RepeatBlock" value="month"> Every x Months</label>
                <label><input type="radio" id="some" name="RepeatBlock" value="year"> Every Year</label>
            </div>
            <div class="mb-3">
                <label for="RepeatFreq" class="form-label">How often does this event repeat?</label>
                <input type="text" class="form-control" id="RepeatFreq" placeholder="Enter the frequency in days" name="RepeatFreq">
            </div>
            <div class="mb-3">
                <label for="RepeatTag" class="form-label">Should there be an anniversary tag (for yearly repeating)?</label>
                <label><input type="radio" id="none" name="RepeatTag" value="True" checked="checked"> Yes</label>
                <label><input type="radio" id="some" name="RepeatTag" value="False"> No</label>
            </div>
        </fieldset>
        <fieldset>
            <legend class="text-primary">Is there an alarm?</legend>
            <div class="mb-3">
                <label for="Alarm" class="form-label">Do you want an alarm this this event?</label>
                <label><input type="radio" id="none" name="Alarm" value="False" checked="checked"> No</label>
                <label><input type="radio" id="some" name="Alarm" value="True"> Yes</label>
            </div>
            <div class="mb-3">
                <label for="dtAlarm" class="form-label">Alarm Date and Time:</label>
                <input type="datetime-local" class="form-control" id="dtAlarm" placeholder="Enter the event date" name="dtAlarm">
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary">Save Event</button>
    </form>
</div>

Views/Calendar/AddTask.cshtml
@model string[]
@{
    ViewData["Title"] = "Add / Edit Event";
}

<div class="container-sm">
    <h3>Enter your event details:</h3>
    <form id="setupForm" action="AddTask" method="post" name="AddTask">
        <input type="hidden" name="guid" value='@((Model != null && Model[0] != null)?(Model[0]):(new Guid()))' />
        <fieldset>
            <legend class="text-primary">Event details:</legend>
            <div class="mb-3">
                <label for="TaskName" class="form-label">Task Name:</label>
                <input type="text" class="form-control" id="TaskName" placeholder="Enter the task name" name="TaskName" required value='@((Model != null)?(Model[1]):(""))'>
            </div>
            <div class="mb-3">
                <label for="TaskDT" class="form-label">Event Due:</label>
                <input type="datetime-local" class="form-control" id="TaskDT" placeholder="Enter the due date/time:" name="TaskDT" required value='@((Model != null)?(Model[2]):(DateTime.Today))' required>
            </div>
        </fieldset>
        <fieldset>
            <legend class="text-primary">Does this task repeat?</legend>
            <div class="mb-3">
                <label for="Repeats" class="form-label">Does this task repeat?</label>
                <label><input type="radio" id="none" name="Repeats" value="False" checked='@((Model != null && Model[6] == "true")?("checked"):(""))'> No</label>
                <label><input type="radio" id="some" name="Repeats" value="True" checked='@((Model != null && Model[6] == "false")?("checked"):(""))'> Yes</label>
            </div>
            <div class="mb-3">
                <label for="RepeatBlock" class="form-label">How often does this task repeat?</label>
                <label><input type="radio" id="none" name="RepeatBlock" value="day" checked='@((Model != null && Model[7] == "day")?("checked"):(""))'> Every x Days</label>
                <label><input type="radio" id="some" name="RepeatBlock" value="month" checked='@((Model != null && Model[7] == "month")?("checked"):(""))'> Every x Months</label>
                <label><input type="radio" id="some" name="RepeatBlock" value="year" checked='@((Model != null && Model[7] == "year")?("checked"):(""))'> Every Year</label>
            </div>
            <div class="mb-3">
                <label for="RepeatFreq" class="form-label">How often does this task repeat?</label>
                <input type="text" class="form-control" id="RepeatFreq" placeholder="Enter the frequency in days" name="RepeatFreq" value='@((Model != null)?(Model[8]):("7"))'>
            </div>
        </fieldset>
        <fieldset>
            <legend class="text-primary">Is this a sub-task?</legend>
            <div class="mb-3">
                <label for="parentGuid" class="form-label">Parent task:</label>
                <select name="parentGuid" id="parentGuid">
                    <option value='@((Model != null && Model[4] != "")?(Model[4]):(""))'>@((Model != null && Model[4] != "")?(Model[4]):(""))</option>
                    @foreach(TaskData td in CalModelView.tasks) {
                        <option value='@td.guid'>@td.TaskName (@td.TaskDT.ToString("yyyy-MM-dd"))</option>
                    }
                </select>
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary">Save Event</button>
    </form>
</div>

Views/Calendar/CalByDate.cshtml
@{
    ViewData["Title"] = @CalModelView.titleText;
}

<section class="row"><!-- class="text-center">-->
    <div class="col-9">
        <div class="row">
            <div class="col">
                <h2>@CalModelView.titleText</h2>
            </div>
            <div class="col">
                <h2 class="rAlign">
                    <a id="addEventLink" href="/Calendar/AddEvent">Add Event</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a id="prevMonth" href="/Calendar/CalByDate?newDate=@CalModelView.prevMonth">&lt;Prev</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a id="nextMonth" href="/Calendar/CalByDate?newDate=@CalModelView.nextMonth">Next&gt;</a>
                </h2>
            </div>
        </div>
        
        <table>
            <thead><tr>
                @foreach(string s in ThisMonth.dowNames) {
                    <th class="text-center">@s</th>
                }
            </tr></thead>
            <tbody>
            @for(var i = 0; i < 6; i++) {
                <tr class="">
                @for(var j = 0; j < 7; j++) {
                    var day = i * 7 + j;
                    <td class='tData @{
                        if(CalModelView.calText[day,1]==CalModelView.currDate) Write("today");
                        if(CalModelView.thisMonth != CalModelView.calText[day,1].Substring(0,6)) Write(" otherMonth");
                    }' id='@CalModelView.calText[day,1]'>@CalModelView.calText[day,0]</td>
                }
                </tr>
            }
            </tbody>
        </table>
    </div>
    <div class="col-3">
        <h2 class="text-center">Your Tasks</h2>
        <h4><a href="/Calendar/AddTask">Add Task</a></h4>
        <table>
            <thead>
                <tr>
                    <th>&#10003;</th>
                    <th>Task Name</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach(TaskData td in CalModelView.tasks) {
                    <tr>
                        <td></td>
                        <td>@td.TaskName</td>
                        <td>@td.TaskDT.ToString("ddd MMM d, yyyy")</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

@section CalNav {
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="CalWeek">Week View</a>
    </li>
}

<script src="~/js/calendar.js" asp-append-version="true"></script>

Views/Calendar/CalWeek.cshtml
@model string[,]
@{
    ViewData["Title"] = @CalModelView.titleText;
}

<section class="row">
    <div class="col-9">
        <div class="row">
            <div class="col">
                <h2>@CalModelView.titleText</h2>
            </div>
            <div class="col">
                <h2 class="rAlign">
                    <a id="addEventLink" href="/Calendar/AddEvent">Add Event</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a id="prevMonth" href="/Calendar/CalWeek?newDate=@CalModelView.prevWeek">&lt;Prev</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a id="nextMonth" href="/Calendar/CalWeek?newDate=@CalModelView.nextWeek">Next&gt;</a>
                </h2>
            </div>
        </div>
        
        <table>
            <thead><tr>
                @foreach(string s in ThisMonth.dowNames) {
                    <th class="text-center">@s</th>
                }
            </tr></thead>
            <tbody>
                <tr class="">
                @for(var j = 0; j < 7; j++) {
                    <td class='tData weekTable' id='@CalModelView.calText[j,1]'>@CalModelView.calText[j,0]</td>
                }
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-3">
        <h4 class="text-center">Your Day</h4>
    </div>
</section>

@section CalNav {
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="CalByDate">Month View</a>
    </li>
}

<script src="~/js/calendar.js" asp-append-version="true"></script>

Views/Calendar/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
@model string[]

<section class="row"><!-- class="text-center">-->
    <div class="col-9">
        <div class="row">
            <div class="col">
                <h2>@Model[42]</h2>
            </div>
            <div class="col">
                <h2 class="rAlign"><a href="/Calendar/CalByDate?newDate=@Model[43]"><</a> <a href="/Calendar/CalByDate?newDate=@Model[44]">></a></h2>
            </div>
        </div>
        
        <table>
            <thead><tr>
                @foreach(string s in ThisMonth.dowNames) {
                    <th class="text-center">@s</th>
                }
            </tr></thead>
            <tbody>
            @for(var i = 0; i < 6; i++) {
                <tr class="tData">
                @for(var j = 0; j < 7; j++) {
                    var day = i * 7 + j;
                    <td>@Model[day]</td>
                }
                </tr>
            }
            </tbody>
        </table>
    </div>
    <div class="col-3">
        <h4 class="text-center">Your Day</h4>
    </div>
</section>